### ISSUE TITLE
User FeedBack

### ISSUE THREAD

**Issue by Aaya-Elsharief** [CA-G12/Api-Project-Ahmed-Ali#15]
## The overall app is realy nice and fun to play with, but we have some notes:
- The search results is added to the existing GIFs in the page.
- The Design should be responsive.
- The code needs some notes and  documentation.
- The project lacks some pure functions.
- We think that is better to separate the fetch function from other functions.

**Comment by AliShbair** [comment]
thank you for your valuable comments!
